import {AppProps} from "next/app";
import Head from "next/head";
import React from "react";
import '../styles/globals.scss';

export default function MyApp({Component, pageProps}: AppProps): JSX.Element {
    return <>
        <Head>
            <title>My App Next</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Component {...pageProps} />;
    </>
}

